### PR TITLE
Clarify how to write feet in fmt_unicsv

### PR DESCRIPTION
**Pull request by jidanni**
For #1015.
By the way e.g., "height" oddly only mentions meters so I do the same.

### CODE REVIEW

**Comment by robertlipe** [comment]
Great. Thank you.

**Comment by tsteven4** [comment]
The unicsv format documentation has bigger issues.  The use of screen elements is not working out for the pdf conversion.

**Comment by GPSBabelDeveloper** [comment]
I haven't looked, but screen was one of the docvook5 changes.

**Comment by tsteven4** [comment]
babelpdf.xsl seems to cause the problem.

**Comment by tsteven4** [comment]
problem came in here https://github.com/GPSBabel/gpsbabel/commit/63b6e0121 
```
Fix build on Catalina, HTML doc formatting improvements (https://github.com/GPSBabel/gpsbabel/pull/759)
* PDF maker: format screen and input same. Shrink padding slightly.
* ```

This change lost the verbatim nature of screen elements, i.e. newlines are lost and the screen content is all jumbled together.

**Comment by tsteven4** [comment]
[screen](https://tdg.docbook.org/tdg/5.0/screen.html) is a verbatim environment.  [userinput](https://tdg.docbook.org/tdg/5.0/userinput.html) is not a verbatim environment, but an inline.  We are applying a [customization](http://www.sagehill.net/docbookxsl/CustomInlines.html) for inline text to a verbatim environment (screen).  

The result is we lose the line breaks and the list of unicsv keywords is all mushed together and thus unreadable.

**Comment by tsteven4** [comment]
We can regain respect for line endings by not matching screen in babelpdf.xsl.  But, when the lines in the screen are too long they get cutoff.

**Comment by tsteven4** [comment]
A fix is described in http://www.sagehill.net/docbookxsl/FittingText.html, although the hyphenation character part doesn't seem to work.

[patch.txt](https://github.com/GPSBabel/gpsbabel/files/10902310/patch.txt)

**Comment by tsteven4** [comment]
For the[ bigger issue](https://github.com/GPSBabel/gpsbabel/pull/1018#issuecomment-1456607119) a potential fix is #1027.
Let's get that settled before we deal with this PR as this PR increases line lengths in a verbatim element and is thus related.

**Comment by robertlipe** [comment]
Approved.

I can regenerate and re-push -development if needed.

**Comment by tsteven4** [comment]
BTW "alt", "ele", "height" are all equivalent and work in meters by default, or in feet with the extension.  "z" also means the same thing, but it is always in meters.

**Comment by tsteven4** [comment]
This resolves #1015

**Pull request merged**
