### PR TITLE
fix interaction between translation and lights.

### PR DESCRIPTION
**Pull request by tsteven4**
When using a language other than English the initial painting of
the gui mainwindow showed the placeholder text for the labels next
to the waypoints, routes and tracks check boxes instead of the
lights.  This was issue #389.

### CODE REVIEW

**Comment by tsteven4** [comment]
The QLabels that dynamically held QPixmaps containing the lights were setup in the UI to contain text.  This was probably done because the images are dynamically scaled and this option isn't available when creating the UI.  Apparently the translator messes with the text and that ends up being displayed initially instead of the dynamically set QPixmaps.

To fix this I changed the UI to contain a placeholder pixmaps instead of text, thus taking the translator out of the picture.  I temporarily used QPixmap::save to save a scaled image in mainwindow.cc.  Then I recolored this scaled image "convert 11scaled.png -colorspace Gray lights.png" and set this in the three QLabels using Qt Designer 5.12.4 on windows.  The rest of the UI changes were made automatically by Qt Designer.

**Comment by tsteven4** [comment]
This fixes #389.

**Comment by robertlipe** [comment]
Very interesting. I was about to ask for help, but that second message made
it all make sense. What a find! Thanx.

RJL

**Comment by tsteven4** [comment]
This fixed #389

**Pull request merged**
