### PR TITLE
make internal_styles.cc a generated file

### PR DESCRIPTION
**Pull request by tsteven4**
on all platforms.
This adds a build requirement for python3.

### CODE REVIEW

**Comment by robertlipe** [comment]
Nice!

**Comment by tsteven4** [comment]
While this worked everywhere I think I have a much better solution..

**Comment by tsteven4** [comment]
Closed without merging in favor of #804

**Comment by GPSBabelDeveloper** [comment]
Are the files linked into the executable it are they tucker inside an app
bundle? (I'm on mobile today...)

Maybe the day of copying/isolating one executable and expecting it to work
the same are over anyway.

**Comment by tsteven4** [comment]
Regarding #804, the way we are doing in they are compiled into the executable much like internal_styles.cc was.  Note the gui was already using the Qt resource system for icons, translations and the gmapbase html file.

https://doc.qt.io/qt-5/resources.html:

> Currently, Qt always stores the data directly in the executable, even on Windows, macOS, and iOS, where the operating system provides native support for resources. This might change in a future Qt release.

https://doc.qt.io/qt-6/resources.html:

> Note: Currently, the Qt resource system does not make use of any system-specific capabilities for handling resources, such as the ones on Windows, macOS, and iOS. This might change in a future Qt release.

**Comment by robertlipe** [comment]
Cool. I'm hip with that, then.
I think there's an expectation that a CLI is self-contained (perhaps
translations aside) where a GUI *expects* to be splattered out in the
filesystem. Given we dynamic link to Qt, that ship has already sailed. I
need to update my own mental model.
Thank you.

**Comment by tsteven4** [comment]
If the Qt implemenation compicated installation I would have favored #803(closed).  As it stands #804(merged) simplifies build, makes minor simplifications to the code, and compiles in all resources like we have always done.  If Qt changes how resources are stored we may need to revisit this.

**Comment by robertlipe** [comment]
Your reasoning is, as usual, solid.

I just needed to fill in my own knowledge gap here.

Thanks!

**Pull request closed without merging**
