### PR TITLE
support doc creation in qmake.

### PR DESCRIPTION
**Pull request by tsteven4**
pass parameters to tools/mkcapabilites instead of
using text replacement in configure.

text replacement in xmldoc/makedoc was unnecessary, directory
creation is handled in the recipee.

there is some foolishness in GPSBabel.pro to allow overriding of
WEB and DOCVERSION on the command line of make.  If those values
are known when running qmake it could be slightly simpler.

### CODE REVIEW

**Comment by tsteven4** [comment]
This eliminates one of the uses of configure, moving us towards its deprecation/removal.
The other issue is library linking which will be addressed separately.

**Comment by tsteven4** [comment]
another issue to be fixed before we can be free of autotools is text replacement in gbversion.h  and gui/setup.iss

**Comment by tsteven4** [comment]
another issue is parallel valgrind(vtesto) for CI.

**Review by GPSBabelDeveloper — APPROVED** [review]
Looks good.
Maybe it's time to get that recipe for building doc out of the build system and into a versioned script in tools/ or such.
Are you sure about that oppo link? Perhaps the site is up but the page is just down right now. (There's a reason we left sourceforge...)
I see now that one of the two systems I use to make doc didn't have the hyphenation library so the 1.7.0 PDF, for example, isn't hyphenated.  Oh, well. Comparing them, they aren't THAT different and I'm not sure how how large our audience for that (huge) doc really is anyway.
With FOP 2.5 being common, is 0.92beta really still in play?

**Comment by tsteven4** [comment]
The comment block was pure cut and paste.  And I think you were the only one on FOP < 1.0.  I'll see if I can find a more up to date reference for hyphenation.

**Comment by GPSBabelDeveloper** [comment]
Yeah, I remember that used to be really painful. I don't think it is now. I see that 'brew' already installs the hyphenation libs for you.

**Comment by tsteven4** [comment]
also need a rule for internal_styles.cc, xcsv_tokens.gperf

**Pull request merged**
