### PR TITLE
prepare for Qt 6.8 deprecations

### PR DESCRIPTION
**Pull request by tsteven4**
This avoids deprecation warning with CMAKE_BUILD_TYPE=Release.  QDateTime is transitioning from Qt::TimeSpec to QTimeZone.  Lightweight times zones for LocalTime and UTC were added in 6.5.0.  Warnings are appearing in pre-release versions of 6.8.0.

~~Also, the exif writer now prefers to establish a timestamp from
GPS_IFD_TAG_DATESTAMP/GPS_IFD_TAG_TIMESTAMP if possible, as the
exif reader does.~~

### CODE REVIEW

**Comment by tsteven4** [comment]
There is also a fix for a QDomDocument deprecation in the gui upgrade check.

**Comment by tsteven4** [comment]
The warnings (and counts) being fixed are:
```
      1 warning: ‘QDateTime QDate::startOfDay(Qt::TimeSpec, int) const’ is deprecated: Pass QTimeZone instead [-Wdeprecated-declarations]
     19 warning: ‘QDateTime::QDateTime(QDate, QTime, Qt::TimeSpec, int)’ is deprecated: Pass QTimeZone instead [-Wdeprecated-declarations]
      1 warning: ‘bool QDomDocument::setContent(const QString&, QString*, int*, int*)’ is deprecated: Use the overload returning ParseResult instead. [-Wdeprecated-declarations]
    101 warning: ‘static QDateTime QDateTime::fromMSecsSinceEpoch(qint64, Qt::TimeSpec, int)’ is deprecated: Pass QTimeZone instead of time-spec, offset [-Wdeprecated-declarations]
      4 warning: ‘static QDateTime QDateTime::fromSecsSinceEpoch(qint64, Qt::TimeSpec, int)’ is deprecated: Pass QTimeZone instead of time-spec, offset [-Wdeprecated-declarations]
      1 warning: ‘void QDateTime::setOffsetFromUtc(int)’ is deprecated: Use setTimeZone() instead [-Wdeprecated-declarations]
      2 warning: ‘void QDateTime::setTimeSpec(Qt::TimeSpec)’ is deprecated: Use setTimeZone() instead [-Wdeprecated-declarations]
      6 warning: ‘void QDateTimeEdit::setTimeSpec(Qt::TimeSpec)’ is deprecated: Use setTimeZone() instead [-Wdeprecated-declarations]
```

**Comment by tsteven4** [comment]
This PR automatically disables the GUI map preview feature if QtWebEngine and/or QtWebChannel are not found.  This allows CI to work with aqt 3.1.18.  https://github.com/miurahr/aqtinstall/issues/803, albeit without QtWebEngine.

6.8.0 builds are added to CI for windows and macos-15 (beta).  The macos-12 build is removed, the runner is being deprecated. https://github.com/actions/runner-images/issues/10721.

**Comment by robertlipe** [comment]
Thanx for handling all these fiddly bits.

**Pull request merged**
