### PR TITLE
use default special member functions for gpx related classes.

### PR DESCRIPTION
**Pull request by tsteven4**
also add some missing .h files to the project.

### CODE REVIEW

**Review by GPSBabelDeveloper — APPROVED** [review]
Could length and elevation be std::optionals instead of out-of-bound values?

Either is ok. This is a good enough of this code.

**Comment by tsteven4** [comment]
std::optional is c++17.  We get away with it in the CLI because we emulate it in src/core/optional.h.

**Comment by tsteven4** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Clones added
============
- gui/gmapdlg.cc  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gpsbabel/gpsbabel/pullRequest?prid=5629456&bid=18438753)

**Comment by tsteven4** [comment]
This was accomplished with #1385.

**Pull request closed without merging**
