### PR TITLE
C-style date and time -> QDateTime in wbt format.

### PR DESCRIPTION
**Pull request by tsteven4**
This also enhances the wbt tests so they look at the timestamps!

### CODE REVIEW

**Comment by robertlipe** [comment]
I thought I deleted wbt ... And navilink.

**Comment by tsteven4** [comment]
Let me check in the fix for navilink, and then lets deprecate them both.

**Comment by tsteven4** [comment]
I'm chasing down time_t and `<ctime>,` getting ready to remove the time_t=0 => invalid crutch.

**Comment by GPSBabelDeveloper** [comment]
Deal. LMK if you want me to be the axe-man as I'm back in pocket now.
(Well, as "in pocket" as I get these days...)

nuke_formats is quite effective, though it misses reference files.
Sometimes we have a reference file used by some OTHER format, so that's
hard to automate.

Now I wonder if I have a computer/branch/work tree somewhere that I forgot
to post and push. More likely I just hallucinated doing it or I thought
about it and fell asleep before doing it or something. I just hate to have
you spending your time on formats that nobody is using.

It does seem like struct tm and friends have lingered on longer than
NEW_STRINGS did. It feels like we've been picking at that scab forever.

**Comment by tsteven4** [comment]
navilink, sbp, sbn are all related.  There is shared code between navilink and both sbp and sbn.  Is only navilink to be deprecated?

**Comment by GPSBabelDeveloper** [comment]
+craig, the czar of windsurfers.

Oh, that's right. Maybe that's whyI started and then backed out.

Kind of like M241 was a hacked-up Holux protocol device, Navilnik takes the
Sirf Binary Protocol and enhances it.

I've long believed that SBN and SBP were used by low-cost logging devices
(the kind one might find on quadcopters) that basically took the
Sirf packets and plopped them into a FAT32 filesystem for later analysis.
We certainly see this basic model applied to the Skytraq and MTK chipsets.
However, skimming blogs and forum posts of the last several years, it seems
that's just not the case. (This probably has to do with Sirf's decade+
patent
<https://www.reuters.com/article/broadcom-sirf-patent/update-1-us-trade-panel-bars-sirf-gps-chips-in-patent-fight-idUSN1538267020090115>
issues
<https://www.gpsworld.com/consumer-oemnewssirf-requests-reexamination-broadcom-patent-ruling-2970/>
and resulting bannination from the U.S.)

The *only* real user I can find of these is the BT-31/60 class of products
and they seem to be almost exclusively windsurfers, but that traffic has
gone to zero in the last 6-8 years. Thus I'm asking our interface to that
community, Craig Bergh, if there are enough remaining active users of the
(Navilink, SBP, SBN) formats to justify their ongoing maintenance costs.

Craig, can you please give us a few sentences of advice here?

Just talking out loud, even in the $.11 CH32V003 space, the cost of a
multi-GB removable storage and writing NMEA sentences has dropped to
nothing, so maybe the days of all these goofy binary logger formats are
just over. Maybe loggers just write NMEA and that's that.

Also, we need better metrics on what is ACTUALLY used in this app. The
Linux camp will flip out and be unrepresented.

**Comment by robertlipe** [comment]
Note to self: I've just spent 90 minutes trying to find Craig and 30 before that trying to not need Craig by independently researching use of these formats. His email bounces, I've tried LinkedIn, Twitter, FB, various WindSurfing sites, and two phone (!) numbers.  One contact form gives an error 500 and the last one is our last hope.

I did submit one help request in a forum and one in email and he's a well known (Surfer of the Year winner) character, so there's still some chance of finding him. It's also possible that his ISP is just being a butt or that something darker has happened. (Google search didn't reveal that if it happened.)

With my memory as it is, I'm just putting it on the permanent record that if I can't find Craig or anyone else representing the Windsurfers in the next few days, these three formats go bye-bye early next week.

**Comment by paulmelis** [comment]
Sorry for necro-commenting, but there still **are** windsurfers using SBN (I have a Locosys GT-31). But I guess I'm too late...

**Pull request merged**
