### PR TITLE
don't create fictitious course and speed values.

### PR DESCRIPTION
**Pull request by tsteven4**
We compute course and speed in track_recompute, which is used
by the kml and gtrnctr writers.  We also compute these in the track
filter with the course speed options.

Both of these algorithms compute the course and speed for a point
based on the time and position of that point and a previous point.
Given that no information from the future is used, the course and
speed of the first point cannot be determined.  This PR introduces
a change so fictitious values for the first point are not generated.

### CODE REVIEW

**Comment by tsteven4** [comment]
This fixes #1019

**Comment by robertlipe** [comment]
Good fix. Thanks.

**Comment by tsteven4** [comment]
Some of the changes in realtime.kml aren't obvious.  They are the result of

1. the random realtime reader generates course base on consecutive points.
2. the kml realtime writer skips points that were within 50 meters of the previous point.
3. the old recompute_track always re-generated course based on the points that weren't skipped.  the new recompute track doesn't recompute course if the original point had a course.  The previous point used in the course calculations by the random realtime reader and the kml realtime writer will be different if we skip a point.

**Comment by GPSBabelDeveloper** [comment]
This is all fine. We have a lot of latitude, IMO, in what's in those
balloons in realtime KML...  The intersection of users of realtime and
those doing computations based on the text in those kml balloons is surely
the null set. Surely. (Google is free to come to me with requirements and a
plan to support it otherwise....)

For #2, this is because Earth of the 3.0 era when this was introduced,
didn't need an indefinite number of drawables plopped on the map while it
was trying to scroll, probably while tethered to an Edge connection. We
were targeting motorists and marine, so 50M steps wasn't unreasonable.

It's pretty rare for non-marine units to provide course that's any more
meaningful than we we get from our own calcs. Wheel and wind sensors aren't
exactly common these days. The difference in course computed from a
previous point or a dropped point is just not THAT significant.



It's good to call these sorts of things out, but I think it's the right
call here to shrug it off.

RJL

**Pull request merged**
