### PR TITLE
de-duplicate format and filter vector display code.

### PR DESCRIPTION
**Pull request by tsteven4**

### CODE REVIEW

**Comment by robertlipe** [comment]
Do you really distrust reference counted smart pointers to track and free
this?

**Comment by tsteven4** [comment]
No smart pointer conversion here, this is all our manual legacy pointer management.  I was going after duplicated blocks in this PR.

**Comment by GPSBabelDeveloper** [comment]
Ok.

**Comment by GPSBabelDeveloper** [comment]
Looks good to me. Thanks.

**Pull request merged**
