### PR TITLE
GUI entry for devices using the cdc_acm driver.

### PR DESCRIPTION
**Pull request by richardmembarth**

### CODE REVIEW

**Comment by GPSBabelDeveloper** [comment]
I'm rebounding from a few weeks on the road, but we replaced this code several months ago with Qt's serial port enumeration, but we've (I've) not made a release since then. Please update to the trunk and confirm that qserialport in a modern Qt is working for you.

**Comment by richardmembarth** [comment]
I've updated to master (the most current branch on github).
It seems that the GUI serial port selection is only extracted from _gui/serial_unix.cc_
Anyways, I'll have no access to my Linux machine until December and will check back then.

**Comment by richardmembarth** [comment]
I checked the latest version on github and it does not use Qt's serial port enumeration: [gui/serial_unix.cc](https://github.com/gpsbabel/gpsbabel/blob/master/gui/serial_unix.cc)
Are you referring to a different repo or branch?

**Comment by GPSBabelDeveloper** [comment]
Apologies. I messed up. There was code that I *thought* was committed that wasn't. Now it is. Can you please see if development trunk works right for you?

**Comment by richardmembarth** [comment]
Thanks for your help. ```/dev/ttyACM0``` is available after the device is plugged in, so I'm going to close the pull request.

**Pull request closed without merging**
