### PR TITLE
fix endianness/packing issues with energympro, globalsat_sport.

### PR DESCRIPTION
**Pull request by tsteven4**
this was motivated by test failures seen at
https://buildd.debian.org/status/fetch.php?pkg=gpsbabel&arch=s390x&ver=1.7.0%2Bds-3&stamp=1594393020&raw=0

### CODE REVIEW

**Comment by tsteven4** [comment]
@jspricke This was motivated by the s390x debian build log cited above.  If you want to fix your regression failure you could use this as a patch.  You seem to be ignoring the error returned by "dh_auto_test: error: make -j2 check VERBOSE=1 returned exit code 2"

**Comment by jspricke** [comment]
Thanks for working on it, I've pushed the patch to Debian. Btw. test are ignored on i386, still:
``
Binary files ./reference/enigma-gpsb.ert and /tmp/gpsbabel.2475/enigma.ert differ
``
https://buildd.debian.org/status/fetch.php?pkg=gpsbabel&arch=i386&ver=1.7.0%2Bds-4&stamp=1596794554&raw=0
Would be great to get that fixed as well.

**Comment by tsteven4** [comment]
@jspricke Thanks for picking up the patch.  Thanks for reporting the i386 regression failure, see #620 for the fix.

**Comment by jspricke** [comment]
Works for Debian: https://buildd.debian.org/status/fetch.php?pkg=gpsbabel&arch=i386&ver=1.7.0%2Bds-5&stamp=1596813332&raw=0

Thanks for fixing it!

**Pull request merged**
