### PR TITLE
support subsecond resolution for trackfilter start/stop options.

### PR DESCRIPTION
**Pull request by tsteven4**

### CODE REVIEW

**Comment by robertlipe** [comment]
LGTM
That code. Is icky.

**Comment by tsteven4** [comment]
Hard to argue.  In general we are not very consistent in the format of similar options, although we do have parse_distance.  In many cases each option was developed in isolation, seemingly according to the whims of the creator.  In this case, making things more complicate isn't making it prettier.  It is too bad QDateTime::fromString doesn't handle subseconds in a useful way, perhaps a better solution is to hide that in a derived class.  This tripped up nmea for a while.

**Comment by GPSBabelDeveloper** [comment]
As usual, we agree.

Throughout the project, M being Meters or Miles, depending on the home
country of the author, remains a regret.

**Comment by tsteven4** [comment]
> That code. Is icky.

Ok, you shamed me into a cleaner implementation.

**Comment by robertlipe** [comment]
I'm not into shame-driven development - the sale of GPSBabel World HQ
to Musk Industries is on hold - but that is a LOT better, so thank you.

**Pull request merged**
