### PR TITLE
Nuke remainder of NEW_STRINGSs.

### PR DESCRIPTION
**Pull request by robertlipe**

### CODE REVIEW

**Comment by tsteven4** [comment]
This needs the main revert, then it has a chance at CI.

**Comment by tsteven4** [comment]
I don't think .qmake.stash should be included.

**Comment by tsteven4** [comment]
the appveyor fails are a floating point mismatch issue on mingw 32, i.e. noise.  But the .qmake.stash needs to go away, probably into .git.ignore.

**Comment by GPSBabelDeveloper** [comment]
These changes have long ago been integrated.

**Pull request closed without merging**
