### PR TITLE
Mechanically remove QStringRef use for QStringView to help with Qt6.

### PR DESCRIPTION
**Pull request by GPSBabelDeveloper**
* Make more string literals encoded at UTF-16 (bloaty-bytes) to
reduce conversions.
* Favor QStringView(Qt6-ism that mirrors C++ standard std::stringview)
over QStringRef (Qt5 hack).

### CODE REVIEW

**Comment by tsteven4** [comment]
It looks like you started this PR without syncing.  Please merge master.

**Comment by GPSBabelDeveloper** [comment]
Yes, I'm experimenting with tools to try to help me make friends with Git and they're doing too much automated crazy stuff. Sorry for the distraction.

**Comment by tsteven4** [comment]
One thing holding us back is that QStringView::split was introduced in 5.15.2.  Other methods introduced late are QStringView::toDouble, etc.

**Comment by GPSBabelDeveloper** [comment]
I think my problem is that I have branches on branches, so i think stuff is committed and merged (this is from October) when it's not near the trunk. I'm on it.

**Comment by tsteven4** [comment]
Yes.  You need to checkout master before you create a branch.  if your on the branch "git merge master" should fix it.

**Comment by tsteven4** [comment]
There are no QStringRef references in master.  This was already done for Qt6 compatibility.

**Review by tsteven4 — CHANGES_REQUESTED** [review]
This should be rejected in its entirety.  I did a merge and compared the results with master.  All the changes, and some improvements on them, are already in master.

**This PR should be closed without merging**.

**Comment by GPSBabelDeveloper** [comment]
This was github debris. The good parts were already captured in other PRs.

**Pull request closed without merging**
