### PR TITLE
add "build" date from CI.

### PR DESCRIPTION
**Pull request by tsteven4**
Actually we add the git author date.  This provides a common date between the CI builds on macos and windows.  The date is only added if GITHUB_SHA exists which implies the repository doesn't have uncommitted changes.

### CODE REVIEW

**Comment by tsteven4** [comment]
I have verified the CI builds on windows and macos behave as expected.
``
/mnt/c/Program\ Files/GPSBabel/gpsbabel.exe -D1
GPSBabel Version: 1.8.0
main: Repository SHA: 7e09a5f5008b22779f2831790e86d156122307b9
main: Date: 2023-04-26T16:49:31Z
main: Compiled with Qt 6.2.4 for architecture x86_64-little_endian-llp64
main: Running with Qt 6.2.4 on Windows 11 Version 2009, x86_64
main: QLocale::system() is en_US
main: QLocale() is en_US
main: QTextCodec::codecForLocale() is System, mib 0
Nothing to do!  Use 'gpsbabel.exe -h' for command-line options.
```
<img width="482" alt="Screenshot 2023-04-26 111654" src="https://user-images.githubusercontent.com/13596209/234653097-e4289ad7-644e-4307-9601-3778a683c5db.png">

**Comment by GPSBabelDeveloper** [comment]
Nicely done. Thanks!

**Comment by tsteven4** [comment]
@GPSBabelDeveloper should we reconnect this with the garmin gdb writer?  For a short time in ancient history it appears we got the build date from CVS, but it has been hard coded for ~12 years.

**Comment by GPSBabelDeveloper** [comment]
I don't think so @tsteven4 ***@***.***>. There was a time when GDB
was moving quickly, when reverse engineering it was a rich field of
experience (pronounced "huge time suck") and when studying a random GDB
file that you were sent, it was useful to know if it was written by
Garmin's own Mapsource (and which) or by random internet program (and which
version thereof).

GDB is, IMO, like Latin. It seems to be frozen in time now. There was some
squawking when I proposed nuking it, but we've not had any complaints (or
blog posts or questions) in many, many years at this point. Basecamp, the
replacement for Mapsource, didn't even support GDB until version 3 and even
now, defaults to GPX. They even discontinue basecamp once (
https://forums.garmin.com/apps-software/mac-windows-software/f/basecamp-windows/127913/basecamp-has-been-discontinued)
but it looks like they released a new version last month. Still, zombie
basecamp ('s GDB files) don't seem to be generating work for anyone, so
let's not perturb the bytestream.

I think that keeping it on life support and disturbing that furball of code
as little as possible (and I know you're talking about like 2 lines of
code, but a turbulence over what we've generated for ~12 years) is the
thing to do.  That code is just full of baffling stuff. e.g. why
does gdb_fread_strlist return a QString and not a QStringList?
Isn't gbfgetcstr_old really just a less comprehsible version of gbfgetpstr?
Is all that mess in gdb_find_wayptq() necessary? What are 'links' about,
anyway? Why is shortname in extra_data? Just every time I go into gdb.cc I
feel tired. (Please do NOT try to answer those questions. Flee!)

I could be wrong on the actual question here. I won't wrestle you over it.
:-)  I just really dislike gdb.cc and don't believe it's strategic enough
to invest in a rewrite that focused on readability.

**Pull request merged**
