### PR TITLE
switch windows release build from 32 bit to 64 bit (only).

### PR DESCRIPTION
**Pull request by tsteven4**
This switches our release build to 64 bits for windows, although 32 bit versions are still build in CI.  This will preclude the use of x86 hardware with our official release.  I have seen estimates of 0.66% market share for 32 bit.

By default the windows install will now go to "Program Files" instead of "Program Files (x86)".

As mentioned in #659, turning off MSVC warning C4267 brings us closer to the warning set we use with gcc/clang (Wall).

### CODE REVIEW

**Comment by robertlipe** [comment]
If it really is .68% we should let it go. The recent pieces on LWN.net really brought home how far into disrepair 32-bit platforms have become in general computing, but I thought there were more pre-Core and low-grade Celeron-is Intel systems out there in use. 

Are there issues with in-place update? Will our Settings from 32-bit still be readable by our "new" app?

**Comment by tsteven4** [comment]
The settings will be preserved unless the user uninstalls the 32 bit app before installing the 64 bit app.  Whenever we run the uninstaller we delete all the registry keys (Flags: uninsdeletekey).

However, if the user has the 32 bit app installed, and then installs the 64 bit app, both apps will be present but windows will only know about the 64 bit app in "add remove programs".  The user can manually resolve this by deleting C:\Program Files (x86)\GPSBabel, or can leave the 32 bit app in place.

By "in-place" update, I assume you mean installing the 64 bit app in C:\Program Files (x86)\GPSBabel on a 64 bit version of windows.  This can be done, but I think it is not what MS intended.  We could end up with both 32 and 64 bit pieces in the folder if something isn't replaced by the new install, e.g. the msvc run time installer.  I think chrome used to do this but now conforms to expectations for new installs, https://www.ghacks.net/2020/06/11/google-chrome-is-soon-going-to-be-installed-in-a-different-directory-on-windows/

**Comment by tsteven4** [comment]
The market share numbers I referred to was from https://www.pcbenchmarks.net/os-marketshare.html

**Comment by tsteven4** [comment]
> However, if the user has the 32 bit app installed, and then installs the 64 bit app, both apps will be present but windows will only know about the 64 bit app in "add remove programs". The user can manually resolve this by deleting C:\Program Files (x86)\GPSBabel, or can leave the 32 bit app in place.

We could probably maintain both uninstallers in that situation, and share registry values, if we change the AppId for the 64 bit version.  We might want to change AppVerName for the 64 bit version to "GPSBabel 1.7.0 (64-bit)"  or "GPSBabel 1.7.0 (x64)" so it would be different in the add/remove programs dialog.  It is too late to change the 32 bit version to "GPSBabel 1.7.0 (32-bit).

**Comment by tsteven4** [comment]
> We could probably maintain both uninstallers in that situation, and share registry values, if we change the AppId for the 64 bit version. We might want to change AppVerName for the 64 bit version to "GPSBabel 1.7.0 (64-bit)" or "GPSBabel 1.7.0 (x64)" so it would be different in the add/remove programs dialog. It is too late to change the 32 bit version to "GPSBabel 1.7.0 (32-bit)

But, running either uninstaller will delete all the registry keys.

**Comment by GPSBabelDeveloper** [comment]
This all sounds pretty reasonable to me. Unlike some apps, we just don't
retain THAT much state in our settings, so I'm OK with there being minor
interference there. I'd think that MOST people will just install an update
and not try to manually reclaim the tiny droppings left over. We could
force the issue and manually nuke the 32-bit version (that may still be
referenced by scripts and automation) but I'd rather leave it there. (We'll
have to be prepared for some people running an older version than they
think: they'll install 1.8.0 but their batch file still calls 1.7.0....)


I do wonder if we should go back to streaming writers instead of apparently
trying to hold all the DOM in VM at once, though. Using > 2GB of RAM to
make a 30MB file seems WAY out of proportion to me, but for one affected
user I'm not digging into measuring it. OTOH, there are some defaults in
our KML writer that are overdue to be changed anyway. All that balloon
stuff should become ExtendedData in modern times, for example.

I'm OK with all of this and stopping here for now. Thanx for your diligence.

RJL

**Comment by tsteven4** [comment]
OK.  To summarize the expected behavior is:  

-  It 32 bit gpsbabel is installed it will be left in place when 64 bit gpsbabel is installed, but the registry (and Control Panel Add/Remove Programs) will be connected to the 64 bit install (or more accurately to the last gpsbabel version installed).  The 32 bit install and it's uninstaller will be orphaned.  If the user wants to clean up they can just delete the 32 bit installation with File Explorer.
- The registry keys are shared, so if the user doesn't run uninstall then they will be preserved and shared between 32 bit and 64 bit versions.   Running either uninstaller deletes are the registry keys where we save settings as it always has.

**Pull request merged**
